apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: launch-katib-mpijob-experiment-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.11, pipelines.kubeflow.org/pipeline_compilation_time: '2022-02-03T13:23:26.654870',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "An example to launch Katib
      Experiment with MPIJob", "inputs": [{"default": "mpi-horovod-mnist", "name":
      "experiment_name", "optional": true, "type": "String"}, {"default": "kubeflow-user-example-com",
      "name": "experiment_namespace", "optional": true, "type": "String"}], "name":
      "Launch Katib MPIJob Experiment"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.11}
spec:
  entrypoint: launch-katib-mpijob-experiment
  templates:
  - name: best-hp
    container:
      args: ['echo Best HyperParameters: {{inputs.parameters.katib-launch-experiment-Best-Parameter-Set}}']
      command: [sh, -c]
      image: library/bash:4.4.23
    inputs:
      parameters:
      - {name: katib-launch-experiment-Best-Parameter-Set}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.11
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: katib-launch-experiment
    container:
      args:
      - --experiment-name
      - '{{inputs.parameters.experiment_name}}'
      - --experiment-namespace
      - '{{inputs.parameters.experiment_namespace}}'
      - --experiment-spec
      - '{"algorithm": {"algorithmName": "bayesianoptimization", "algorithmSettings":
        [{"name": "random_state", "value": "10"}]}, "maxFailedTrialCount": 3, "maxTrialCount":
        6, "objective": {"goal": 0.01, "objectiveMetricName": "loss", "type": "minimize"},
        "parallelTrialCount": 2, "parameters": [{"feasibleSpace": {"max": "0.003",
        "min": "0.001"}, "name": "lr", "parameterType": "double"}, {"feasibleSpace":
        {"max": "150", "min": "50", "step": "10"}, "name": "num-steps", "parameterType":
        "int"}], "trialTemplate": {"failureCondition": "status.conditions.#(type==\"Failed\")#|#(status==\"True\")#",
        "primaryContainerName": "mpi-launcher", "primaryPodLabels": {"mpi-job-role":
        "launcher"}, "successCondition": "status.conditions.#(type==\"Succeeded\")#|#(status==\"True\")#",
        "trialParameters": [{"description": "Learning rate for the training model",
        "name": "learningRate", "reference": "lr"}, {"description": "Number of training
        steps", "name": "numberSteps", "reference": "num-steps"}], "trialSpec": {"apiVersion":
        "kubeflow.org/v1", "kind": "MPIJob", "spec": {"cleanPodPolicy": "Running",
        "mpiReplicaSpecs": {"Launcher": {"replicas": 1, "template": {"metadata": {"annotations":
        {"sidecar.istio.io/inject": "false"}}, "spec": {"containers": [{"args": ["-np",
        "2", "--allow-run-as-root", "-bind-to", "none", "-map-by", "slot", "-x", "LD_LIBRARY_PATH",
        "-x", "PATH", "-mca", "pml", "ob1", "-mca", "btl", "^openib", "python", "/examples/tensorflow_mnist.py",
        "--lr", "${trialParameters.learningRate}", "--num-steps", "${trialParameters.numberSteps}"],
        "command": ["mpirun"], "image": "docker.io/kubeflow/mpi-horovod-mnist", "name":
        "mpi-launcher", "resources": {"limits": {"cpu": "500m", "memory": "2Gi"}}}]}}},
        "Worker": {"replicas": 2, "template": {"metadata": {"annotations": {"sidecar.istio.io/inject":
        "false"}}, "spec": {"containers": [{"image": "docker.io/kubeflow/mpi-horovod-mnist",
        "name": "mpi-worker", "resources": {"limits": {"cpu": "500m", "memory": "4Gi"}}}]}}}},
        "slotsPerWorker": 1}}}}'
      - --experiment-timeout-minutes
      - '60'
      - --delete-after-done
      - "True"
      - --output-file
      - /tmp/outputs/Best_Parameter_Set/data
      command: [python, src/launch_experiment.py]
      image: docker.io/kubeflowkatib/kubeflow-pipelines-launcher
    inputs:
      parameters:
      - {name: experiment_name}
      - {name: experiment_namespace}
    outputs:
      parameters:
      - name: katib-launch-experiment-Best-Parameter-Set
        valueFrom: {path: /tmp/outputs/Best_Parameter_Set/data}
      artifacts:
      - {name: katib-launch-experiment-Best-Parameter-Set, path: /tmp/outputs/Best_Parameter_Set/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.11
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Katib
          Experiment launcher", "implementation": {"container": {"args": ["--experiment-name",
          {"inputValue": "Experiment Name"}, "--experiment-namespace", {"inputValue":
          "Experiment Namespace"}, "--experiment-spec", {"inputValue": "Experiment
          Spec"}, "--experiment-timeout-minutes", {"inputValue": "Experiment Timeout
          Minutes"}, "--delete-after-done", {"inputValue": "Delete Finished Experiment"},
          "--output-file", {"outputPath": "Best Parameter Set"}], "command": ["python",
          "src/launch_experiment.py"], "image": "docker.io/kubeflowkatib/kubeflow-pipelines-launcher"}},
          "inputs": [{"default": "", "description": "Experiment name", "name": "Experiment
          Name", "type": "String"}, {"default": "anonymous", "description": "Experiment
          namespace", "name": "Experiment Namespace", "type": "String"}, {"default":
          "{}", "description": "Experiment specification in dict format", "name":
          "Experiment Spec", "type": "JsonObject"}, {"default": 1440, "description":
          "Time in minutes to wait for the Experiment to complete", "name": "Experiment
          Timeout Minutes", "type": "Integer"}, {"default": "True", "description":
          "Whether to delete the Experiment after it is finished", "name": "Delete
          Finished Experiment", "type": "Bool"}], "name": "Katib - Launch Experiment",
          "outputs": [{"description": "The hyperparameter set of the best Experiment
          Trial", "name": "Best Parameter Set", "type": "JsonObject"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "a93c64b052e810a0d0d0ada3f28a03b3e45e5a3e3bf03272d4bf6c67d5e14bac", "url":
          "https://raw.githubusercontent.com/kubeflow/pipelines/master/components/kubeflow/katib-launcher/component.yaml"}',
        pipelines.kubeflow.org/arguments.parameters: '{"Delete Finished Experiment":
          "True", "Experiment Name": "{{inputs.parameters.experiment_name}}", "Experiment
          Namespace": "{{inputs.parameters.experiment_namespace}}", "Experiment Spec":
          "{\"algorithm\": {\"algorithmName\": \"bayesianoptimization\", \"algorithmSettings\":
          [{\"name\": \"random_state\", \"value\": \"10\"}]}, \"maxFailedTrialCount\":
          3, \"maxTrialCount\": 6, \"objective\": {\"goal\": 0.01, \"objectiveMetricName\":
          \"loss\", \"type\": \"minimize\"}, \"parallelTrialCount\": 2, \"parameters\":
          [{\"feasibleSpace\": {\"max\": \"0.003\", \"min\": \"0.001\"}, \"name\":
          \"lr\", \"parameterType\": \"double\"}, {\"feasibleSpace\": {\"max\": \"150\",
          \"min\": \"50\", \"step\": \"10\"}, \"name\": \"num-steps\", \"parameterType\":
          \"int\"}], \"trialTemplate\": {\"failureCondition\": \"status.conditions.#(type==\\\"Failed\\\")#|#(status==\\\"True\\\")#\",
          \"primaryContainerName\": \"mpi-launcher\", \"primaryPodLabels\": {\"mpi-job-role\":
          \"launcher\"}, \"successCondition\": \"status.conditions.#(type==\\\"Succeeded\\\")#|#(status==\\\"True\\\")#\",
          \"trialParameters\": [{\"description\": \"Learning rate for the training
          model\", \"name\": \"learningRate\", \"reference\": \"lr\"}, {\"description\":
          \"Number of training steps\", \"name\": \"numberSteps\", \"reference\":
          \"num-steps\"}], \"trialSpec\": {\"apiVersion\": \"kubeflow.org/v1\", \"kind\":
          \"MPIJob\", \"spec\": {\"cleanPodPolicy\": \"Running\", \"mpiReplicaSpecs\":
          {\"Launcher\": {\"replicas\": 1, \"template\": {\"metadata\": {\"annotations\":
          {\"sidecar.istio.io/inject\": \"false\"}}, \"spec\": {\"containers\": [{\"args\":
          [\"-np\", \"2\", \"--allow-run-as-root\", \"-bind-to\", \"none\", \"-map-by\",
          \"slot\", \"-x\", \"LD_LIBRARY_PATH\", \"-x\", \"PATH\", \"-mca\", \"pml\",
          \"ob1\", \"-mca\", \"btl\", \"^openib\", \"python\", \"/examples/tensorflow_mnist.py\",
          \"--lr\", \"${trialParameters.learningRate}\", \"--num-steps\", \"${trialParameters.numberSteps}\"],
          \"command\": [\"mpirun\"], \"image\": \"docker.io/kubeflow/mpi-horovod-mnist\",
          \"name\": \"mpi-launcher\", \"resources\": {\"limits\": {\"cpu\": \"500m\",
          \"memory\": \"2Gi\"}}}]}}}, \"Worker\": {\"replicas\": 2, \"template\":
          {\"metadata\": {\"annotations\": {\"sidecar.istio.io/inject\": \"false\"}},
          \"spec\": {\"containers\": [{\"image\": \"docker.io/kubeflow/mpi-horovod-mnist\",
          \"name\": \"mpi-worker\", \"resources\": {\"limits\": {\"cpu\": \"500m\",
          \"memory\": \"4Gi\"}}}]}}}}, \"slotsPerWorker\": 1}}}}", "Experiment Timeout
          Minutes": "60"}'}
  - name: launch-katib-mpijob-experiment
    inputs:
      parameters:
      - {name: experiment_name}
      - {name: experiment_namespace}
    dag:
      tasks:
      - name: best-hp
        template: best-hp
        dependencies: [katib-launch-experiment]
        arguments:
          parameters:
          - {name: katib-launch-experiment-Best-Parameter-Set, value: '{{tasks.katib-launch-experiment.outputs.parameters.katib-launch-experiment-Best-Parameter-Set}}'}
      - name: katib-launch-experiment
        template: katib-launch-experiment
        arguments:
          parameters:
          - {name: experiment_name, value: '{{inputs.parameters.experiment_name}}'}
          - {name: experiment_namespace, value: '{{inputs.parameters.experiment_namespace}}'}
  arguments:
    parameters:
    - {name: experiment_name, value: mpi-horovod-mnist}
    - {name: experiment_namespace, value: kubeflow-user-example-com}
  serviceAccountName: pipeline-runner



